services:
  mysql:
    image: mysql:8.0.36
    container_name: mysql-8.0.36-v1
    cap_add:
      - SYS_NICE
    restart: no
    environment:
      - MYSQL_DATABASE=booking_db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      -  ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis-stack-server-v2
    restart: no
    ports:
      - '6379:6379'
    networks:
      - default
  booking-back-end-service:
    container_name: booking-back-end-service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - default
    depends_on:
      - mysql
      - redis
networks:
  default:
    name: booking-back-end-service
volumes:
    mysql_data: