# application-dev
# spring config
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://${JDBC_ADDRESS:localhost}:3306/booking_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${USERNAME:root}
    password: ${PASSWORD:root}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  mail:
    from: Booking
    host: smtp.gmail.com
    port: 587
    username: ${USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

outbound:
  google:
    identity:
      url: https://oauth2.googleapis.com
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      redirect-uri: http://localhost:5173/authentication
      grant-type: authorization_code
    user:
      url: https://www.googleapis.com
  facebook:
    identity:
      url: https://graph.facebook.com
      client-id: ${FACEBOOK_CLIENT_ID}
      client-secret: ${FACEBOOK_CLIENT_SECRET}
      redirect-uri: http://localhost:5173/authentication
      grant-type: authorization_code
    user:
      url: https://graph.facebook.com

# swagger config
openapi:
  service:
    api-docs: booking-back-end-service
    title: Booking Back-End API DOCS
    version: v1.0
    server: http://localhost:${server.port}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

# jwt secret key
jwt:
  expirationTime: 15
  expirationDay: 7
  accessToken: ${ACCESS_TOKEN_SECRET}
  refreshToken: ${REFRESH_TOKEN_SECRET}

admin-user:
  email: nguyentrungk285@gmail.com
  password: 18082003
admin-profile:
  firstName: Kay
  lastName: Nguyen
  countryCode: +84
  phone: +84378277559
  gender: MALE
  address: 40/4 Hang Tre, Long Thanh My, TP.Thu Duc, TP.Ho Chi Minh

google:
  map:
    api-key: ${GOOGLE_MAPS_API_KEY}