# application

server:
  port: 8081
  servlet:
    context-path: /booking-api/v1

spring:
  application:
    name: booking-back-end-service
  profiles:
    active: @spring.profiles.active@

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    web: info
    root: info
