# application

server:
  port: 8081
  servlet:
    context-path: /booking-api/v1

spring:
  application:
    name: booking-back-end-service
  profiles:
    active: @spring.profiles.active@
  web:
    resources:
      static-locations: file:uploads/
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 10MB

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    web: info
    root: info
